const AishiteCard = document.querySelector('#aishite-card')
const LarawanCard = document.querySelector('#larawan-card')
const BalangigaCard = document.querySelector('#balangiga-card')
const BalerCard = document.querySelector('#baler-card')
const ThirdWorldCard = document.querySelector('#thirdWorld-card')
const Batch81Card = document.querySelector('#batch81-card')
const BonifacioCard = document.querySelector('#bonifacio-card')
const Dekada70Card = document.querySelector('#dekada70-card')
const GoyoCard = document.querySelector('#goyo-card')
const GiveUpCard = document.querySelector('#giveUp-card')
const LunaCard = document.querySelector('#luna-card')
const RizalCard = document.querySelector('#rizal-card')
const LiwayCard = document.querySelector('#liway-card')
const GamuGamoCard = document.querySelector('#gamuGamo-card')
const MLCard = document.querySelector('#ml-card')
const NinoyCard = document.querySelector('#ninoy-card')
const OroCard = document.querySelector('#oro-card')
const SakayCard = document.querySelector('#sakay-card')
const SisterCard = document.querySelector('#sister-card')
const WalangDiyosCard = document.querySelector('#walangDiyos-card')


const AishiteCard1 = document.querySelector('#aishite-card1')
const LarawanCard1 = document.querySelector('#larawan-card1')
const BalangigaCard1 = document.querySelector('#balangiga-card1')
const BalerCard1 = document.querySelector('#baler-card1')
const ThirdWorldCard1 = document.querySelector('#thirdWorld-card1')
const Batch81Card1 = document.querySelector('#batch81-card1')
const BonifacioCard1 = document.querySelector('#bonifacio-card1')
const Dekada70Card1 = document.querySelector('#dekada70-card1')
const GoyoCard1 = document.querySelector('#goyo-card1')
const GiveUpCard1 = document.querySelector('#giveUp-card1')
const LunaCard1 = document.querySelector('#luna-card1')
const RizalCard1 = document.querySelector('#rizal-card1')
const LiwayCard1 = document.querySelector('#liway-card1')
const GamuGamoCard1 = document.querySelector('#gamuGamo-card1')
const MLCard1 = document.querySelector('#ml-card1')
const NinoyCard1 = document.querySelector('#ninoy-card1')
const OroCard1 = document.querySelector('#oro-card1')
const SakayCard1 = document.querySelector('#sakay-card1')
const SisterCard1 = document.querySelector('#sister-card1')
const WalangDiyosCard1 = document.querySelector('#walangDiyos-card1')

var MRTCBValue = document.querySelector('#mrtcbSelect').value
var StreamingValue = document.querySelector('#streamingSelect').value

function sortFunction() {
  var SortValue = document.getElementById('sortSelect').value
  if (SortValue === "1") {
    AishiteCard.style.display = 'block'
    LarawanCard.style.display = 'block'
    BalangigaCard.style.display = 'block'
    BalerCard.style.display = 'block'
    ThirdWorldCard.style.display = 'block'
    Batch81Card.style.display = 'block'
    BonifacioCard.style.display = 'block'
    Dekada70Card.style.display = 'block'
    GoyoCard.style.display = 'block'
    GiveUpCard.style.display = 'block'
    LunaCard.style.display = 'block'
    RizalCard.style.display = 'block'
    LiwayCard.style.display = 'block'
    GamuGamoCard.style.display = 'block'
    MLCard.style.display = 'block'
    NinoyCard.style.display = 'block'
    OroCard.style.display = 'block'
    SakayCard.style.display = 'block'
    SisterCard.style.display = 'block'
    WalangDiyosCard.style.display = 'block'

    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'
  } else if (SortValue === "2") {
    AishiteCard1.style.display = 'block'
    LarawanCard1.style.display = 'block'
    BalangigaCard1.style.display = 'block'
    BalerCard1.style.display = 'block'
    ThirdWorldCard1.style.display = 'block'
    Batch81Card1.style.display = 'block'
    BonifacioCard1.style.display = 'block'
    Dekada70Card1.style.display = 'block'
    GoyoCard1.style.display = 'block'
    GiveUpCard1.style.display = 'block'
    LunaCard1.style.display = 'block'
    RizalCard1.style.display = 'block'
    LiwayCard1.style.display = 'block'
    GamuGamoCard1.style.display = 'block'
    MLCard1.style.display = 'block'
    NinoyCard1.style.display = 'block'
    OroCard1.style.display = 'block'
    SakayCard1.style.display = 'block'
    SisterCard1.style.display = 'block'
    WalangDiyosCard1.style.display = 'block'

    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'
  }

}

function familyDynamics() {
  var SortValue = document.getElementById('sortSelect').value
  if (SortValue === "1") {
    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'block'
    BalangigaCard.style.display = 'block'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'block'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'block'
    GamuGamoCard.style.display = 'block'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'block'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'block'

    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'
  } else if (SortValue === "2") {
    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'block'
    BalangigaCard1.style.display = 'block'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'block'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'block'
    GamuGamoCard1.style.display = 'block'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'block'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'block'

    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'
  }

}



function humanRights() {
  var SortValue = document.getElementById('sortSelect').value
  if (SortValue === "1") {
    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'block'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'block'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'block'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'block'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'block'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'block'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'block'

    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'
  } else if (SortValue === "2") {
    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'block'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'block'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'block'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'block'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'block'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'block'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'block'

    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'
  }
}


function documentary() {
  var SortValue = document.getElementById('sortSelect').value
  if (SortValue === "1") {
    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'block'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'block'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'

    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'
  } else if (SortValue === "2") {
    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'block'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'block'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'

    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'
  }

}

function nationBuilding() {
  var SortValue = document.getElementById('sortSelect').value
  if (SortValue === "1") {
    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'block'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'block'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'block'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'block'
    RizalCard.style.display = 'block'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'block'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'block'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'

    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'
  } else if (SortValue === "2") {
    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'block'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'block'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'block'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'block'
    RizalCard1.style.display = 'block'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'block'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'block'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'

    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'
  }
}

function bioPic() {
  var SortValue = document.getElementById('sortSelect').value
  if (SortValue === "1") {
    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'block'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'block'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'block'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'block'
    RizalCard.style.display = 'block'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'block'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'

    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'
  } else if (SortValue === "2") {
    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'block'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'block'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'block'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'block'
    RizalCard1.style.display = 'block'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'block'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'

    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'
  }

}

function colonialism() {
  var SortValue = document.getElementById('sortSelect').value
  if (SortValue === "1") {
    AishiteCard.style.display = 'block'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'block'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'block'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'block'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'block'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'

    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'
  } else if (SortValue === "2") {
    AishiteCard1.style.display = 'block'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'block'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'block'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'block'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'block'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'

    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'
  }

}

function women() {
  var SortValue = document.getElementById('sortSelect').value
  if (SortValue === "1") {
    AishiteCard.style.display = 'block'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'block'
    GamuGamoCard.style.display = 'block'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'block'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'block'
    WalangDiyosCard.style.display = 'none'

    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'
  } else if (SortValue === "2") {
    AishiteCard1.style.display = 'block'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'block'
    GamuGamoCard1.style.display = 'block'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'block'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'block'
    WalangDiyosCard1.style.display = 'none'

    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'
  }

}

function politics() {
  var SortValue = document.getElementById('sortSelect').value
  if (SortValue === "1") {
    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'block'
    Dekada70Card.style.display = 'block'
    GoyoCard.style.display = 'block'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'block'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'block'
    NinoyCard.style.display = 'block'
    OroCard.style.display = 'block'
    SakayCard.style.display = 'block'
    SisterCard.style.display = 'block'
    WalangDiyosCard.style.display = 'none'

    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'none'
    Dekada70Card1.style.display = 'none'
    GoyoCard1.style.display = 'none'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'none'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'none'
    NinoyCard1.style.display = 'none'
    OroCard1.style.display = 'none'
    SakayCard1.style.display = 'none'
    SisterCard1.style.display = 'none'
    WalangDiyosCard1.style.display = 'none'
  } else if (SortValue === "2") {
    AishiteCard1.style.display = 'none'
    LarawanCard1.style.display = 'none'
    BalangigaCard1.style.display = 'none'
    BalerCard1.style.display = 'none'
    ThirdWorldCard1.style.display = 'none'
    Batch81Card1.style.display = 'none'
    BonifacioCard1.style.display = 'block'
    Dekada70Card1.style.display = 'block'
    GoyoCard1.style.display = 'block'
    GiveUpCard1.style.display = 'none'
    LunaCard1.style.display = 'block'
    RizalCard1.style.display = 'none'
    LiwayCard1.style.display = 'none'
    GamuGamoCard1.style.display = 'none'
    MLCard1.style.display = 'block'
    NinoyCard1.style.display = 'block'
    OroCard1.style.display = 'block'
    SakayCard1.style.display = 'block'
    SisterCard1.style.display = 'block'
    WalangDiyosCard1.style.display = 'none'


    AishiteCard.style.display = 'none'
    LarawanCard.style.display = 'none'
    BalangigaCard.style.display = 'none'
    BalerCard.style.display = 'none'
    ThirdWorldCard.style.display = 'none'
    Batch81Card.style.display = 'none'
    BonifacioCard.style.display = 'none'
    Dekada70Card.style.display = 'none'
    GoyoCard.style.display = 'none'
    GiveUpCard.style.display = 'none'
    LunaCard.style.display = 'none'
    RizalCard.style.display = 'none'
    LiwayCard.style.display = 'none'
    GamuGamoCard.style.display = 'none'
    MLCard.style.display = 'none'
    NinoyCard.style.display = 'none'
    OroCard.style.display = 'none'
    SakayCard.style.display = 'none'
    SisterCard.style.display = 'none'
    WalangDiyosCard.style.display = 'none'
  }

}
